// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

export default function handler(req, res) {
	res.status(200).json([
		{
			Category: "Photography",
			"Event name": "DSLR Photography",
			Registration: 150,
			"Payment Links": "",
		},
		{
			Category: "Photography",
			"Event name": "Mobile Photography",
			Registration: 100,
			"Payment Links": "",
		},
		{
			Category: "Music",
			"Event name": "Solo Singing (Indian)",
			Registration: 150,
			"Payment Links": "",
		},
		{
			Category: "Music",
			"Event name": "Solo Singing (Western)",
			Registration: 150,
			"Payment Links": "",
		},
		{
			Category: "Music",
			"Event name": "Instrumental",
			Registration: 150,
			"Payment Links": "",
		},
		{
			Category: "Music",
			"Event name": "Battle of Bands",
			Registration: 1500,
			"Payment Links": "",
		},
		{
			Category: "Music",
			"Event name": "Rap Battle",
			Registration: 150,
			"Payment Links": "",
		},
		{
			Category: "Music",
			"Event name": "Duet Singing",
			Registration: 300,
			"Payment Links": "",
		},
		{
			Category: "Music",
			"Event name": "Group singing",
			Registration: 500,
			"Payment Links": "",
		},
		{
			Category: "Muses",
			"Event name": "Logo Redesign",
			Registration: 100,
			"Payment Links": "",
		},
		{
			Category: "Muses",
			"Event name": "Reel it",
			Registration: 100,
			"Payment Links": "",
		},
		{
			Category: "Muses",
			"Event name": "MS paint",
			Registration: 100,
			"Payment Links": "",
		},
		{
			Category: "Theatre",
			"Event name": "Improv",
			Registration: 300,
			"Payment Links": "",
		},
		{
			Category: "Theatre",
			"Event name": "Streetplay",
			Registration: 500,
			"Payment Links": "",
		},
		{
			Category: "Theatre",
			"Event name": "Mime",
			Registration: 500,
			"Payment Links": "",
		},
		{
			Category: "Theatre",
			"Event name": "Monologue",
			Registration: 150,
			"Payment Links": "",
		},
		{
			Category: "Theatre",
			"Event name": "Mad Ads",
			Registration: 500,
			"Payment Links": "",
		},
		{
			Category: "Dance",
			"Event name": "Kick n Crew(western group dance)",
			Registration: 600,
			"Payment Links": "",
		},
		{
			Category: "Dance",
			"Event name": "Two for Tango",
			Registration: 300,
			"Payment Links": "",
		},
		{
			Category: "Dance",
			"Event name": "Switch Foot",
			Registration: 150,
			"Payment Links": "",
		},
		{
			Category: "Dance",
			"Event name": "1 vs 1",
			Registration: 150,
			"Payment Links": "",
		},
		{
			Category: "Dance",
			"Event name": "Kinkini(classical solo)",
			Registration: 150,
			"Payment Links": "",
		},
		{
			Category: "Literary",
			"Event name": "Trivia Island",
			Registration: 300,
			"Payment Links": "",
		},
		{
			Category: "Literary",
			"Event name": "BOTS",
			Registration: 150,
			"Payment Links": "",
		},
		{
			Category: "Literary",
			"Event name": "El Tale Mocktail",
			Registration: 150,
			"Payment Links": "",
		},
		{
			Category: "Literary",
			"Event name": "War of Words",
			Registration: 300,
			"Payment Links": "",
		},
		{
			Category: "Gaming",
			"Event name": "Call of Duty Mobile",
			Registration: 150,
			"Payment Links": "",
		},
		{
			Category: "Gaming",
			"Event name": "Counter Strike",
			Registration: 500,
			"Payment Links": "",
		},
		{
			Category: "Gaming",
			"Event name": "NFS",
			Registration: 150,
			"Payment Links": "",
		},
		{
			Category: "Gaming",
			"Event name": "FIFA",
			Registration: 150,
			"Payment Links": "",
		},
		{
			Category: "Gaming",
			"Event name": "BGMI/PUBG",
			Registration: 400,
			"Payment Links": "",
		},
		{
			Category: "Fashion",
			"Event name": "Fashion Show",
			Registration: 2000,
			"Payment Links": "",
		},
		{
			Category: "Informal",
			"Event name": "Mr. Fit",
			Registration: 150,
			"Payment Links": "",
		},
		{
			Category: "Informal",
			"Event name": "Food Hunt",
			Registration: 300,
			"Payment Links": "",
		},
		{
			Category: "Informal",
			"Event name": "Hogathon",
			Registration: 150,
			"Payment Links": "",
		},
		{
			Category: "Informal",
			"Event name": "Stand-up Comedy",
			Registration: 150,
			"Payment Links": "",
		},
		{
			Category: "Kannada",
			"Event name": "Best Puneeth Impression",
			Registration: 100,
			"Payment Links": "",
		},
		{
			Category: "Kannada",
			"Event name": "KGF",
			Registration: 100,
			"Payment Links": "",
		},
		{
			Category: "Kannada",
			"Event name": "Hemmeya Kannadiga",
			Registration: 200,
			"Payment Links": "",
		},
		{
			Category: "Kannada",
			"Event name": "Bhaavasangama",
			Registration: 200,
			"Payment Links": "",
		},
		{
			Category: "Art",
			"Event name": "Face Painting",
			Registration: 150,
			"Payment Links": "",
		},
		{
			Category: "Art",
			"Event name": "Book Cover",
			Registration: 150,
			"Payment Links": "",
		},
		{
			Category: "Art",
			"Event name": "Ditch your brush",
			Registration: 150,
			"Payment Links": "",
		},
		{
			Category: "Art",
			"Event name": "Charcoal Art",
			Registration: 150,
			"Payment Links": "",
		},
		{
			Category: "CSE",
			"Event name": "Code Raiders",
			Registration: 300,
			"Payment Links": "",
		},
		{
			Category: "ISE",
			"Event name": "Codical Chairs",
			Registration: 200,
			"Payment Links": "",
		},
		{
			Category: "ECE",
			"Event name": "Circuit Hunt",
			Registration: 300,
			"Payment Links": "",
		},
		{
			Category: "EEE",
			"Event name": "Debate on EV's",
			Registration: 300,
			"Payment Links": "",
		},
		{
			Category: "CIVIL",
			"Event name": "Autocad",
			Registration: 150,
			"Payment Links": "",
		},
		{
			Category: "MECH",
			"Event name": "Robo Ignitors",
			Registration: 500,
			"Payment Links": "",
		},
		{
			Category: "MBA",
			"Event name": "Best Manager",
			Registration: 200,
			"Payment Links": "",
		},
		{
			Category: "MCA",
			"Event name": "Digital Scavenger",
			Registration: 200,
			"Payment Links": "",
		},
		{
			Category: "Events total",
			"Event name": "",
			Registration: 14700,
			"Payment Links": "",
		},
	]);
}
